version: '3.4'

services:
  company:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"

  sqldata:
    environment:
      - SA_PASSWORD=vV5r9tn0M4@
      - ACCEPT_EULA=Y
      - LETSMEETSERVER_CONNECTIONSTRING=Server=localhost,1440;Initial Catalog=master;User ID=SA;Password=vV5r9tn0M4@;TrustServerCertificate=trueIntegrated Security=false
    ports:
      - "1450:1433"

  cache:
    ports:
       - '6379:6379'

  rabbitmq:
    ports:
        - "5672:5672"
        - "15672:15672"