version: '3.4'

services:
  company:
    image: company
    build:
      context: .
      dockerfile: LetsMeet.Company.WebApi/Dockerfile

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest

  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

  rabbitmq:
    container_name: rabbitmq
    hostname: "my-rabbitmq-server"
    image: rabbitmq:3-management
