CREATE TABLE [dbo].[Likes]
(
	[LikeId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [UserIdF] UNIQUEIDENTIFIER NULL, 
    [PostIdF] UNIQUEIDENTIFIER NULL,

    CONSTRAINT [FK_Like_ToUsers] FOREIGN KEY ([UserIdF]) REFERENCES [Users]([UserId]), 
    CONSTRAINT [FK_Like_ToPost] FOREIGN KEY ([PostIdF]) REFERENCES [Post]([PostId])
)
