CREATE TABLE [dbo].[Role]
(
	[RoleId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [RoleName] NVARCHAR(50) NULL, 
    [IsVerified] INT NULL, 
    [UserIdF] UNIQUEIDENTIFIER NULL, 
    [OwnerIdF] UNIQUEIDENTIFIER NULL

    CONSTRAINT [FK_Role_ToUsers] FOREIGN KEY ([UserIdF]) REFERENCES [Users]([UserId]),
    CONSTRAINT [FK_Role_ToOwner] FOREIGN KEY ([OwnerIdF]) REFERENCES [Owner]([OwnerId])
)
